- hosts: "*"
  become: yes
  tasks:
    - name: set up repository
      apt:
        name: "{{item}}"
        state: present
        update_cache: yes
      loop:
        - ca-certificates
        - curl
        - gnupg
        - lsb-release

    - name: Dockers official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: add docker repository to apt
      apt_repository: 
        repo: deb https://download.docker.com/linux/ubuntu jammy stable
        state: present

    - name: install docker
      apt:
        name: "{{item}}"
        state: latest
        update_cache: yes
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io
    
    - name: check docker is active
      service:
        name: docker
        state: started
        enabled: yes

    - name: Ensure group "docker" exists
      ansible.builtin.group:
        name: docker
        state: present

    - name: adding ubu to docker group
      user:
        name: ubu
        groups: docker
        append: yes
      
    - name: install docker compose
      apt:
        name: docker-compose-plugin
        state: latest
        update_cache: yes


    